### ISSUE TITLE
[v1.2.0] Visual Studio 2022 build errors, need help

### ISSUE THREAD

**Issue by kkzi** [r3dl3g/guipp#1]
I really like the idea about modern c++ gui wheel, it's pretty awesome, so I want to try it out, but I'm having some build issues. 

**ENV**: windows 10 x64 / Visual Studio 2022 / guipp v1.2.0

**build steps**
cmake .. -G"Visual Studio 17 2022" -DCMAKE_CONFIGURATION_TYPES=Debug;Release -DGUIPP_BUILD_DEPENDENT_LIBS=ON
cmake --build .

**issues**
1.  D:\Code\clockapp\libs\guipp\gui\win\native_win32.cpp(351,19): error C2059: syntax error: '='

i try to fix it:

![image](https://user-images.githubusercontent.com/34122458/172358176-e59dd08c-eb4d-403e-8b66-4981e647a3c3.png)

2. D:\Code\clockapp\libs\guipp\gui/layout/layout_container.inl(93,22): error C2039: 'add': is not a member of 'gui::layout::scroll_view' [D:\Code\clockapp\build\gui\ctrl\ctrl.vcxproj]

i can't fix it, need you help :) .

![image](https://user-images.githubusercontent.com/34122458/172358073-6e1ed23f-30e5-4369-b0c5-f7e57b1eaf03.png)

**Comment by r3dl3g** [comment]
Oh dear, My bad,

Someone is interested in my code and I push an unfinished version on github. What a shame.

I have a new version 1.2.1 released that now compiles on Windows again.
Please pull the latest version and don't forget to update the submodules too (git submodules update).

Please note that the version number may be a bit too optimistic.
The whole project is still very much in flow and it is not yet complete in my opinion.
But it is good enough to build working, stable C++ application for Windows and Linux.

I have also created working applications for MacOS, Android (native) and ubports (all three using QtBase as a bottom layer).
But the build-chains are yet not really ready and some manual work is necessary.

I would be happy to receive further feedback.

Greetings
 Redleg
